import os

from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer
)

from reportlab.lib.styles import (
    getSampleStyleSheet
)


def generate_report(
    filename,
    decision,
    confidence,
    risk,
    applicant_income,
    loan_amount
):

    # Create folder if path contains one
    folder = os.path.dirname(filename)

    if folder:
        os.makedirs(
            folder,
            exist_ok=True
        )

    doc = SimpleDocTemplate(
        filename
    )

    styles = getSampleStyleSheet()

    content = []

    # Title

    content.append(
        Paragraph(
            "AI-Powered Loan Assessment Report",
            styles["Title"]
        )
    )

    content.append(
        Spacer(1, 20)
    )

    # Report Details

    content.append(
        Paragraph(
            f"<b>Decision:</b> {decision}",
            styles["Normal"]
        )
    )

    content.append(
        Spacer(1, 8)
    )

    content.append(
        Paragraph(
            f"<b>Confidence:</b> {confidence:.2f}%",
            styles["Normal"]
        )
    )

    content.append(
        Spacer(1, 8)
    )

    content.append(
        Paragraph(
            f"<b>Risk Level:</b> {risk}",
            styles["Normal"]
        )
    )

    content.append(
        Spacer(1, 8)
    )

    content.append(
        Paragraph(
            f"<b>Applicant Income:</b> ₹{applicant_income:,}",
            styles["Normal"]
        )
    )

    content.append(
        Spacer(1, 8)
    )

    content.append(
        Paragraph(
            f"<b>Loan Amount:</b> ₹{loan_amount:,}",
            styles["Normal"]
        )
    )

    content.append(
        Spacer(1, 20)
    )

    content.append(
        Paragraph(
            "This report was automatically generated by the "
            "AI Loan Approval & Credit Risk Assessment System.",
            styles["Italic"]
        )
    )

    doc.build(content)